name: green_rewards
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  qr_flutter: ^4.1.0
  mobile_scanner: ^5.0.0
  shared_preferences: ^2.2.2
  path_provider: ^2.1.2
  permission_handler: ^11.3.1
  image_gallery_saver: ^2.0.3
  url_launcher: ^6.2.6
  http: ^1.2.0
  image_picker: ^1.0.4
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  ios: true
  android: true
  image_path: assets/icon/app_icon.png
  remove_alpha_ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo_truong.png
    - assets/icon/app_icon.png
    - assets/icon/app_icon2.png
    - assets/images/partners/1.png
    - assets/images/partners/2.png
    - assets/images/partners/3.png
    - assets/images/partners/4.png
    - assets/images/partners/5.png
    - assets/images/partners/6.png
    - assets/images/partners/7.png
    - assets/images/partners/8.png
    - assets/images/partners/9.png
    - assets/images/partners/10.png
